---
- name: Creating Vault raft storage folder.
  file:
    dest: '{{ vault_path }}/vault'
    state: 'directory'
    owner: 'vault'
    group: 'vault'
    mode: '0750'

- name: Vault configuration file transfer.
  template:
    src: 'vault.hcl.j2'
    dest: '/etc/vault.d/vault.hcl'
    owner: 'vault'
    group: 'vault'
    mode: '0640'
  register: vault_config_update
