---
- name: Creating Vault folder.
  file:
    dest: '{{ item }}'
    state: 'directory'
    owner: 'vault'
    group: 'vault'
    mode: '0750'
  loop:
    - '{{ vault_path }}/vault'
    - '/home/vault'

- name: Vault configuration file transfer.
  template:
    src: 'vault.hcl.j2'
    dest: '/etc/vault.d/vault.hcl'
    owner: 'vault'
    group: 'vault'
    mode: '0640'
  register: vault_config_update
