- name: Add the group vault.
  group:
    name: "{{ vault_arg.user }}"
    gid: '{{ vault_arg.uid }}'

- name: Add the user vault.
  user:
    name: '{{ vault_arg.user }}'
    comment: '{{ vault_arg.user }}'
    create_home: 'yes'
    shell: '/sbin/nologin'
    uid: '{{ vault_arg.uid }}'
    group: '{{ vault_arg.user }}'

- name: Check current vault version.
  command: '/usr/local/bin/vault --version'
  register: vault_current_version
  changed_when: false
  failed_when: false

- name: Delete existing vault version if different.
  file:
    path: '/usr/local/bin/vault'
    state: absent
  when:
    - vault_current_version.stdout is defined
    - vault_version not in vault_current_version.stdout

- name: Install HashiCorp vault.
  unarchive:
    src: '{{ vault_soft_url }}/vault/{{ vault_version }}/vault_{{ vault_version }}_{{ ansible_system | lower }}_{{ vault_architecture[ansible_architecture] }}.zip'
    dest: '/usr/local/bin'
    owner: '{{ vault_arg.user }}'
    group: '{{ vault_arg.user }}'
    mode: '0755'
    remote_src: 'yes'
    validate_certs: 'no'
  when:
    - vault_current_version.rc == 2 or vault_version not in vault_current_version.stdout
  register: vault_upgrade
  until: vault_upgrade is succeeded
  retries: 5
  delay: 2

- name: Creating vault folder.
  file:
    dest: '{{ item }}'
    state: 'directory'
    owner: '{{ vault_arg.user }}'
    group: '{{ vault_arg.user }}'
    mode: '0750'
  loop:
    - '/etc/vault'
    - '{{ vault_path }}/vault'