---
- name: Include tasks for specific OS.
  include: '{{ ansible_os_family }}.yml'

- name: Include firewall tasks.
  include: 'firewall.yml'

- name: Installation the Vault.
  include: 'install.yml'

- name: Include certificate tasks.
  include: 'certificates.yml'
  when: vault_tls | bool

- name: Configuration the Vault.
  include: 'configureation.yml'

- name: Reload the Vault service.
  shell: echo ''
  notify: 'Ensure vault service is enabled'
  when: vault_upgrade is changed or vault_config_update is changed

- name: Force the handler to run immediately.
  meta: flush_handlers

- name: Include initialize tasks.
  include: 'init.yml'
  when: vault_servers[0] in ansible_default_ipv4.address

- name: Include unseal tasks.
  include: 'unseal.yml'
  when: vault_init_key is defined

- name: Include audit tasks.
  include: 'audit.yml'
  when:
    - vault_root_token is defined
    - vault_servers[0] in ansible_default_ipv4.address

- name: Include backup tasks.
  include: 'backup.yml'
  when: vault_root_token is defined

- name: Include auto-unseal task.
  include: 'auto-unseal.yml'
  when: vault_init_key is defined

- name: Reload the Vault service.
  shell: echo ''
  notify: 'Ensure vault service is enabled'
  when: vault_systemd_update is changed

- name: Registered with HashiCorp Consul.
  include: 'register.yml'
  when: 
    - exporter_is_install | bool
    - consul_public_register | bool
