---
- name: Unsealing the Vault members.
  uri:
    url: '{% if vault_tls | bool %}https{% else %}http{% endif %}://{{ ansible_default_ipv4.address }}:{{ vault_port_arg.api }}/v1/sys/unseal'
    method: 'PUT'
    timeout: '30'
    body: '{"key":"{{ item }}"}'
    body_format: 'json'
    status_code: '200'
    headers:
      X-Requested-By: '{{ ansible_default_ipv4.address }}'
      cache-control: 'no-cache'
    validate_certs: 'no'
  environment:
    no_proxy: '{{ ansible_default_ipv4.address }}'
  loop: '{{ vault_init_key }}'
  register: vault_unseal_status
  until: vault_unseal_status.status == 200
  retries: 10
  delay: 2
  no_log: true
