---
- name: Enable vault service.
  systemd:
    name: 'vault.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'
  async: 1
  poll: 0
  listen: Ensure vault service is enabled